name: 'supabase-embeddings-generator'
description: 'Generate embeddings from your Knowledge Base to use with Supabase Vector.'
author: 'Supabase'
inputs:
  supabase-url:
    required: true
    description: 'Your Supabase project URL'
  supabase-service-role-key:
    required: true
    description: 'Your Supabase SERVICE_ROLE key'
  embedding-model:
    required: false
    description: 'The embedding model to use. Defaults to text-embedding-ada-002'
  openai-key:
    required: true
    description: 'Your OpenAI API key'
  docs-root-path:
    required: true
    description: 'The path to the root of your knowledge base or docs folder'
    default: 'docs'
runs:
  using: 'node16'
  main: 'dist/index.js'
